# Site settings
title: Bosnian Guy at Flatiron
header-img: img/home-bg.png
email: senadhadrovic@gmail.com
copyright_name: senhad
description: > # this means to ignore newlines until "baseurl:"
  Musings from my journey to learn coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  senhad
learn_profile: senhad
email_username: senadhadrovic@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
